title: Un jeu pour moi

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "games"
    values:
      layout: "game"
  -
    scope:
      path: ""
      type: "events"
    values:
      layout: "event"

collections:
  games:
    output: true
    permalink: /jeux/:title
  
  events:
    output: true
    permalink: /evenements/:title

 
